spring:
  application:
    name: greeting-service

management:
  endpoints:
    web:
      exposure:
        include:
        - '*'    
greeting-service:
    greeting: "qa diz: Olá"
    default-value: "Mundo"
    
